### ISSUE TITLE
Maybe it's a typo?

### ISSUE THREAD

**Issue by enderneko** [RKI027/ffxiv-huntmaps-maker#5]
annotate.py line 132
`for name in self.zone_info:`
should be
`for name in self._zones:`

**Comment by enderneko** [comment]
and line 228

**Comment by enderneko** [comment]
BTW may I translate this mod into Chinese and share it on a Chinese forum?
Of course I'll note the link of this project.

**Comment by RKI027** [comment]
line 132: old refactoring missed that line, thank you!
line 228: this was already correct, or do i miss something?

as for translating in Chinese, sure.
