### ISSUE TITLE
Data use request

### ISSUE THREAD

**Issue by LittleNightmare** [RKI027/ffxiv-huntmaps-maker#6]
thanks for you sharing this tool, it help me a lot. 

I want to ask May I your your data in other tool? We are designing a [tool](https://github.com/VergilGao/XIVHunter.GoodMemory) that try to predict S-rank spawn point? 

I cannot find other data of hunt monster like yours could use directly

**Comment by RKI027** [comment]
Thanks for asking, feel free to use the data indeed.

Fyi, ARR, HW and SB comes from a cross-reference I did between [Cable Monkey](https://cablemonkey.us/huntmap2), [consolegameswiki](https://ffxiv.consolegameswiki.com/wiki) and [Faloop](https://faloop.app). ShB and EW from Faloop.
